package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer idaccount;
     private User user;
     private String description;
     private double balance;
     private double creditLimit;
     private int status;
     private Set transactions = new HashSet(0);

    public Account() {
    }

	
    public Account(User user, double balance, double creditLimit, int status) {
        this.user = user;
        this.balance = balance;
        this.creditLimit = creditLimit;
        this.status = status;
    }
    public Account(User user, String description, double balance, double creditLimit, int status, Set transactions) {
       this.user = user;
       this.description = description;
       this.balance = balance;
       this.creditLimit = creditLimit;
       this.status = status;
       this.transactions = transactions;
    }
   
    public Integer getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(Integer idaccount) {
        this.idaccount = idaccount;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public double getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(double creditLimit) {
        this.creditLimit = creditLimit;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


