package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idaddress;
     private Town town;
     private String name;
     private String address;
     private String latitude;
     private String longitude;
     private int status;
     private String contactNumber;
     private Set deliveriesForToAddress = new HashSet(0);
     private Set parcelsForTo = new HashSet(0);
     private Set deliveriesForFromAddress = new HashSet(0);
     private Set parcelsForFrom = new HashSet(0);
     private Set userHasAddresses = new HashSet(0);

    public Address() {
    }

	
    public Address(Town town, String name, String address, int status, String contactNumber) {
        this.town = town;
        this.name = name;
        this.address = address;
        this.status = status;
        this.contactNumber = contactNumber;
    }
    public Address(Town town, String name, String address, String latitude, String longitude, int status, String contactNumber, Set deliveriesForToAddress, Set parcelsForTo, Set deliveriesForFromAddress, Set parcelsForFrom, Set userHasAddresses) {
       this.town = town;
       this.name = name;
       this.address = address;
       this.latitude = latitude;
       this.longitude = longitude;
       this.status = status;
       this.contactNumber = contactNumber;
       this.deliveriesForToAddress = deliveriesForToAddress;
       this.parcelsForTo = parcelsForTo;
       this.deliveriesForFromAddress = deliveriesForFromAddress;
       this.parcelsForFrom = parcelsForFrom;
       this.userHasAddresses = userHasAddresses;
    }
   
    public Integer getIdaddress() {
        return this.idaddress;
    }
    
    public void setIdaddress(Integer idaddress) {
        this.idaddress = idaddress;
    }
    public Town getTown() {
        return this.town;
    }
    
    public void setTown(Town town) {
        this.town = town;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public Set getDeliveriesForToAddress() {
        return this.deliveriesForToAddress;
    }
    
    public void setDeliveriesForToAddress(Set deliveriesForToAddress) {
        this.deliveriesForToAddress = deliveriesForToAddress;
    }
    public Set getParcelsForTo() {
        return this.parcelsForTo;
    }
    
    public void setParcelsForTo(Set parcelsForTo) {
        this.parcelsForTo = parcelsForTo;
    }
    public Set getDeliveriesForFromAddress() {
        return this.deliveriesForFromAddress;
    }
    
    public void setDeliveriesForFromAddress(Set deliveriesForFromAddress) {
        this.deliveriesForFromAddress = deliveriesForFromAddress;
    }
    public Set getParcelsForFrom() {
        return this.parcelsForFrom;
    }
    
    public void setParcelsForFrom(Set parcelsForFrom) {
        this.parcelsForFrom = parcelsForFrom;
    }
    public Set getUserHasAddresses() {
        return this.userHasAddresses;
    }
    
    public void setUserHasAddresses(Set userHasAddresses) {
        this.userHasAddresses = userHasAddresses;
    }




}


