package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryStatus generated by hbm2java
 */
public class DeliveryStatus  implements java.io.Serializable {


     private Integer iddeliveryStatus;
     private String status;
     private Set parcels = new HashSet(0);
     private Set deliveries = new HashSet(0);

    public DeliveryStatus() {
    }

	
    public DeliveryStatus(String status) {
        this.status = status;
    }
    public DeliveryStatus(String status, Set parcels, Set deliveries) {
       this.status = status;
       this.parcels = parcels;
       this.deliveries = deliveries;
    }
   
    public Integer getIddeliveryStatus() {
        return this.iddeliveryStatus;
    }
    
    public void setIddeliveryStatus(Integer iddeliveryStatus) {
        this.iddeliveryStatus = iddeliveryStatus;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getParcels() {
        return this.parcels;
    }
    
    public void setParcels(Set parcels) {
        this.parcels = parcels;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }




}


