package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer iddelivery;
     private DeliveryStatus deliveryStatus;
     private Parcel parcel;
     private Address addressByFromAddress;
     private Address addressByToAddress;
     private Date fromDateTime;
     private Date toDateTime;
     private Boolean isAccept;

    public Delivery() {
    }

	
    public Delivery(DeliveryStatus deliveryStatus, Parcel parcel, Address addressByFromAddress, Date fromDateTime) {
        this.deliveryStatus = deliveryStatus;
        this.parcel = parcel;
        this.addressByFromAddress = addressByFromAddress;
        this.fromDateTime = fromDateTime;
    }
    public Delivery(DeliveryStatus deliveryStatus, Parcel parcel, Address addressByFromAddress, Address addressByToAddress, Date fromDateTime, Date toDateTime, Boolean isAccept) {
       this.deliveryStatus = deliveryStatus;
       this.parcel = parcel;
       this.addressByFromAddress = addressByFromAddress;
       this.addressByToAddress = addressByToAddress;
       this.fromDateTime = fromDateTime;
       this.toDateTime = toDateTime;
       this.isAccept = isAccept;
    }
   
    public Integer getIddelivery() {
        return this.iddelivery;
    }
    
    public void setIddelivery(Integer iddelivery) {
        this.iddelivery = iddelivery;
    }
    public DeliveryStatus getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(DeliveryStatus deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public Parcel getParcel() {
        return this.parcel;
    }
    
    public void setParcel(Parcel parcel) {
        this.parcel = parcel;
    }
    public Address getAddressByFromAddress() {
        return this.addressByFromAddress;
    }
    
    public void setAddressByFromAddress(Address addressByFromAddress) {
        this.addressByFromAddress = addressByFromAddress;
    }
    public Address getAddressByToAddress() {
        return this.addressByToAddress;
    }
    
    public void setAddressByToAddress(Address addressByToAddress) {
        this.addressByToAddress = addressByToAddress;
    }
    public Date getFromDateTime() {
        return this.fromDateTime;
    }
    
    public void setFromDateTime(Date fromDateTime) {
        this.fromDateTime = fromDateTime;
    }
    public Date getToDateTime() {
        return this.toDateTime;
    }
    
    public void setToDateTime(Date toDateTime) {
        this.toDateTime = toDateTime;
    }
    public Boolean getIsAccept() {
        return this.isAccept;
    }
    
    public void setIsAccept(Boolean isAccept) {
        this.isAccept = isAccept;
    }




}


