package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device  implements java.io.Serializable {


     private Integer iddevice;
     private String model;
     private String brand;
     private int status;
     private String udid;
     private Set userHasDevices = new HashSet(0);

    public Device() {
    }

	
    public Device(String model, String brand, int status, String udid) {
        this.model = model;
        this.brand = brand;
        this.status = status;
        this.udid = udid;
    }
    public Device(String model, String brand, int status, String udid, Set userHasDevices) {
       this.model = model;
       this.brand = brand;
       this.status = status;
       this.udid = udid;
       this.userHasDevices = userHasDevices;
    }
   
    public Integer getIddevice() {
        return this.iddevice;
    }
    
    public void setIddevice(Integer iddevice) {
        this.iddevice = iddevice;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getUdid() {
        return this.udid;
    }
    
    public void setUdid(String udid) {
        this.udid = udid;
    }
    public Set getUserHasDevices() {
        return this.userHasDevices;
    }
    
    public void setUserHasDevices(Set userHasDevices) {
        this.userHasDevices = userHasDevices;
    }




}


