package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Distance generated by hbm2java
 */
public class Distance  implements java.io.Serializable {


     private Integer iddistance;
     private String distanceType;
     private int status;
     private Set rateSheets = new HashSet(0);

    public Distance() {
    }

	
    public Distance(String distanceType, int status) {
        this.distanceType = distanceType;
        this.status = status;
    }
    public Distance(String distanceType, int status, Set rateSheets) {
       this.distanceType = distanceType;
       this.status = status;
       this.rateSheets = rateSheets;
    }
   
    public Integer getIddistance() {
        return this.iddistance;
    }
    
    public void setIddistance(Integer iddistance) {
        this.iddistance = iddistance;
    }
    public String getDistanceType() {
        return this.distanceType;
    }
    
    public void setDistanceType(String distanceType) {
        this.distanceType = distanceType;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getRateSheets() {
        return this.rateSheets;
    }
    
    public void setRateSheets(Set rateSheets) {
        this.rateSheets = rateSheets;
    }




}


