package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PackageType generated by hbm2java
 */
public class PackageType  implements java.io.Serializable {


     private Integer idpackageType;
     private String packageType;
     private int status;
     private Set parcels = new HashSet(0);
     private Set rateSheets = new HashSet(0);

    public PackageType() {
    }

	
    public PackageType(String packageType, int status) {
        this.packageType = packageType;
        this.status = status;
    }
    public PackageType(String packageType, int status, Set parcels, Set rateSheets) {
       this.packageType = packageType;
       this.status = status;
       this.parcels = parcels;
       this.rateSheets = rateSheets;
    }
   
    public Integer getIdpackageType() {
        return this.idpackageType;
    }
    
    public void setIdpackageType(Integer idpackageType) {
        this.idpackageType = idpackageType;
    }
    public String getPackageType() {
        return this.packageType;
    }
    
    public void setPackageType(String packageType) {
        this.packageType = packageType;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getParcels() {
        return this.parcels;
    }
    
    public void setParcels(Set parcels) {
        this.parcels = parcels;
    }
    public Set getRateSheets() {
        return this.rateSheets;
    }
    
    public void setRateSheets(Set rateSheets) {
        this.rateSheets = rateSheets;
    }




}


