package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parcel generated by hbm2java
 */
public class Parcel  implements java.io.Serializable {


     private Integer idparcel;
     private DeliveryStatus deliveryStatus;
     private PackageType packageType;
     private Address addressByTo;
     private Address addressByFrom;
     private float weight;
     private float height;
     private float length;
     private float width;
     private Date date;
     private String refNumber;
     private String curruntLocationLongitude;
     private String curruntLocationLatitude;
     private Set deliveries = new HashSet(0);
     private Set transactions = new HashSet(0);

    public Parcel() {
    }

	
    public Parcel(DeliveryStatus deliveryStatus, PackageType packageType, Address addressByTo, Address addressByFrom, float weight, float height, float length, float width, Date date, String curruntLocationLongitude, String curruntLocationLatitude) {
        this.deliveryStatus = deliveryStatus;
        this.packageType = packageType;
        this.addressByTo = addressByTo;
        this.addressByFrom = addressByFrom;
        this.weight = weight;
        this.height = height;
        this.length = length;
        this.width = width;
        this.date = date;
        this.curruntLocationLongitude = curruntLocationLongitude;
        this.curruntLocationLatitude = curruntLocationLatitude;
    }
    public Parcel(DeliveryStatus deliveryStatus, PackageType packageType, Address addressByTo, Address addressByFrom, float weight, float height, float length, float width, Date date, String refNumber, String curruntLocationLongitude, String curruntLocationLatitude, Set deliveries, Set transactions) {
       this.deliveryStatus = deliveryStatus;
       this.packageType = packageType;
       this.addressByTo = addressByTo;
       this.addressByFrom = addressByFrom;
       this.weight = weight;
       this.height = height;
       this.length = length;
       this.width = width;
       this.date = date;
       this.refNumber = refNumber;
       this.curruntLocationLongitude = curruntLocationLongitude;
       this.curruntLocationLatitude = curruntLocationLatitude;
       this.deliveries = deliveries;
       this.transactions = transactions;
    }
   
    public Integer getIdparcel() {
        return this.idparcel;
    }
    
    public void setIdparcel(Integer idparcel) {
        this.idparcel = idparcel;
    }
    public DeliveryStatus getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(DeliveryStatus deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public PackageType getPackageType() {
        return this.packageType;
    }
    
    public void setPackageType(PackageType packageType) {
        this.packageType = packageType;
    }
    public Address getAddressByTo() {
        return this.addressByTo;
    }
    
    public void setAddressByTo(Address addressByTo) {
        this.addressByTo = addressByTo;
    }
    public Address getAddressByFrom() {
        return this.addressByFrom;
    }
    
    public void setAddressByFrom(Address addressByFrom) {
        this.addressByFrom = addressByFrom;
    }
    public float getWeight() {
        return this.weight;
    }
    
    public void setWeight(float weight) {
        this.weight = weight;
    }
    public float getHeight() {
        return this.height;
    }
    
    public void setHeight(float height) {
        this.height = height;
    }
    public float getLength() {
        return this.length;
    }
    
    public void setLength(float length) {
        this.length = length;
    }
    public float getWidth() {
        return this.width;
    }
    
    public void setWidth(float width) {
        this.width = width;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getRefNumber() {
        return this.refNumber;
    }
    
    public void setRefNumber(String refNumber) {
        this.refNumber = refNumber;
    }
    public String getCurruntLocationLongitude() {
        return this.curruntLocationLongitude;
    }
    
    public void setCurruntLocationLongitude(String curruntLocationLongitude) {
        this.curruntLocationLongitude = curruntLocationLongitude;
    }
    public String getCurruntLocationLatitude() {
        return this.curruntLocationLatitude;
    }
    
    public void setCurruntLocationLatitude(String curruntLocationLatitude) {
        this.curruntLocationLatitude = curruntLocationLatitude;
    }
    public Set getDeliveries() {
        return this.deliveries;
    }
    
    public void setDeliveries(Set deliveries) {
        this.deliveries = deliveries;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


