package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Town generated by hbm2java
 */
public class Town  implements java.io.Serializable {


     private Integer idtown;
     private Zone zone;
     private String name;
     private int status;
     private String longitude;
     private String latitude;
     private Set addresses = new HashSet(0);

    public Town() {
    }

	
    public Town(Zone zone, String name, int status, String longitude, String latitude) {
        this.zone = zone;
        this.name = name;
        this.status = status;
        this.longitude = longitude;
        this.latitude = latitude;
    }
    public Town(Zone zone, String name, int status, String longitude, String latitude, Set addresses) {
       this.zone = zone;
       this.name = name;
       this.status = status;
       this.longitude = longitude;
       this.latitude = latitude;
       this.addresses = addresses;
    }
   
    public Integer getIdtown() {
        return this.idtown;
    }
    
    public void setIdtown(Integer idtown) {
        this.idtown = idtown;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }




}


