package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private Integer idtransactionType;
     private String transactionType;
     private Set transactions = new HashSet(0);

    public TransactionType() {
    }

	
    public TransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public TransactionType(String transactionType, Set transactions) {
       this.transactionType = transactionType;
       this.transactions = transactions;
    }
   
    public Integer getIdtransactionType() {
        return this.idtransactionType;
    }
    
    public void setIdtransactionType(Integer idtransactionType) {
        this.idtransactionType = idtransactionType;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


