package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer idtransaction;
     private Account account;
     private Parcel parcel;
     private TransactionType transactionType;
     private String description;
     private double amount;
     private int status;
     private Date date;

    public Transaction() {
    }

    public Transaction(Account account, Parcel parcel, TransactionType transactionType, String description, double amount, int status, Date date) {
       this.account = account;
       this.parcel = parcel;
       this.transactionType = transactionType;
       this.description = description;
       this.amount = amount;
       this.status = status;
       this.date = date;
    }
   
    public Integer getIdtransaction() {
        return this.idtransaction;
    }
    
    public void setIdtransaction(Integer idtransaction) {
        this.idtransaction = idtransaction;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Parcel getParcel() {
        return this.parcel;
    }
    
    public void setParcel(Parcel parcel) {
        this.parcel = parcel;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


