package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UserHasVehicle generated by hbm2java
 */
public class UserHasVehicle  implements java.io.Serializable {


     private Integer iduserHasVehicle;
     private Vehicle vehicle;
     private User user;
     private int status;
     private Date startDate;
     private Date endDate;

    public UserHasVehicle() {
    }

	
    public UserHasVehicle(Vehicle vehicle, User user, int status, Date startDate) {
        this.vehicle = vehicle;
        this.user = user;
        this.status = status;
        this.startDate = startDate;
    }
    public UserHasVehicle(Vehicle vehicle, User user, int status, Date startDate, Date endDate) {
       this.vehicle = vehicle;
       this.user = user;
       this.status = status;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public Integer getIduserHasVehicle() {
        return this.iduserHasVehicle;
    }
    
    public void setIduserHasVehicle(Integer iduserHasVehicle) {
        this.iduserHasVehicle = iduserHasVehicle;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


