package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private UserRole userRole;
     private UserStatus userStatus;
     private String nic;
     private String name;
     private String username;
     private String password;
     private String apiKey;
     private String email;
     private String resetToken;
     private Set userHasDevices = new HashSet(0);
     private Set userHasVehicles = new HashSet(0);
     private Set userHasAddresses = new HashSet(0);
     private Set userHasRateSheets = new HashSet(0);
     private Set accounts = new HashSet(0);

    public User() {
    }

	
    public User(UserRole userRole, UserStatus userStatus, String name, String username, String password) {
        this.userRole = userRole;
        this.userStatus = userStatus;
        this.name = name;
        this.username = username;
        this.password = password;
    }
    public User(UserRole userRole, UserStatus userStatus, String nic, String name, String username, String password, String apiKey, String email, String resetToken, Set userHasDevices, Set userHasVehicles, Set userHasAddresses, Set userHasRateSheets, Set accounts) {
       this.userRole = userRole;
       this.userStatus = userStatus;
       this.nic = nic;
       this.name = name;
       this.username = username;
       this.password = password;
       this.apiKey = apiKey;
       this.email = email;
       this.resetToken = resetToken;
       this.userHasDevices = userHasDevices;
       this.userHasVehicles = userHasVehicles;
       this.userHasAddresses = userHasAddresses;
       this.userHasRateSheets = userHasRateSheets;
       this.accounts = accounts;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public UserStatus getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(UserStatus userStatus) {
        this.userStatus = userStatus;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getApiKey() {
        return this.apiKey;
    }
    
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getResetToken() {
        return this.resetToken;
    }
    
    public void setResetToken(String resetToken) {
        this.resetToken = resetToken;
    }
    public Set getUserHasDevices() {
        return this.userHasDevices;
    }
    
    public void setUserHasDevices(Set userHasDevices) {
        this.userHasDevices = userHasDevices;
    }
    public Set getUserHasVehicles() {
        return this.userHasVehicles;
    }
    
    public void setUserHasVehicles(Set userHasVehicles) {
        this.userHasVehicles = userHasVehicles;
    }
    public Set getUserHasAddresses() {
        return this.userHasAddresses;
    }
    
    public void setUserHasAddresses(Set userHasAddresses) {
        this.userHasAddresses = userHasAddresses;
    }
    public Set getUserHasRateSheets() {
        return this.userHasRateSheets;
    }
    
    public void setUserHasRateSheets(Set userHasRateSheets) {
        this.userHasRateSheets = userHasRateSheets;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


