package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0



/**
 * UserRoleHasActionId generated by hbm2java
 */
public class UserRoleHasActionId  implements java.io.Serializable {


     private int userRoleIduserRole;
     private int actionIdaction;

    public UserRoleHasActionId() {
    }

    public UserRoleHasActionId(int userRoleIduserRole, int actionIdaction) {
       this.userRoleIduserRole = userRoleIduserRole;
       this.actionIdaction = actionIdaction;
    }
   
    public int getUserRoleIduserRole() {
        return this.userRoleIduserRole;
    }
    
    public void setUserRoleIduserRole(int userRoleIduserRole) {
        this.userRoleIduserRole = userRoleIduserRole;
    }
    public int getActionIdaction() {
        return this.actionIdaction;
    }
    
    public void setActionIdaction(int actionIdaction) {
        this.actionIdaction = actionIdaction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRoleHasActionId) ) return false;
		 UserRoleHasActionId castOther = ( UserRoleHasActionId ) other; 
         
		 return (this.getUserRoleIduserRole()==castOther.getUserRoleIduserRole())
 && (this.getActionIdaction()==castOther.getActionIdaction());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserRoleIduserRole();
         result = 37 * result + this.getActionIdaction();
         return result;
   }   


}


