package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer iduserRole;
     private String role;
     private int status;
     private Set userRoleHasActions = new HashSet(0);
     private Set users = new HashSet(0);

    public UserRole() {
    }

	
    public UserRole(String role, int status) {
        this.role = role;
        this.status = status;
    }
    public UserRole(String role, int status, Set userRoleHasActions, Set users) {
       this.role = role;
       this.status = status;
       this.userRoleHasActions = userRoleHasActions;
       this.users = users;
    }
   
    public Integer getIduserRole() {
        return this.iduserRole;
    }
    
    public void setIduserRole(Integer iduserRole) {
        this.iduserRole = iduserRole;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getUserRoleHasActions() {
        return this.userRoleHasActions;
    }
    
    public void setUserRoleHasActions(Set userRoleHasActions) {
        this.userRoleHasActions = userRoleHasActions;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


