package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0



/**
 * UserHasRateSheet generated by hbm2java
 */
public class UserHasRateSheet  implements java.io.Serializable {


     private Integer iduserHasRateSheet;
     private RateSheet rateSheet;
     private User user;
     private int state;

    public UserHasRateSheet() {
    }

    public UserHasRateSheet(RateSheet rateSheet, User user, int state) {
       this.rateSheet = rateSheet;
       this.user = user;
       this.state = state;
    }
   
    public Integer getIduserHasRateSheet() {
        return this.iduserHasRateSheet;
    }
    
    public void setIduserHasRateSheet(Integer iduserHasRateSheet) {
        this.iduserHasRateSheet = iduserHasRateSheet;
    }
    public RateSheet getRateSheet() {
        return this.rateSheet;
    }
    
    public void setRateSheet(RateSheet rateSheet) {
        this.rateSheet = rateSheet;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }




}


