package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private VehicleType vehicleType;
     private String vehicleNumber;
     private int status;
     private Date licenceUpto;
     private Date insuaranceUpto;
     private Set userHasVehicles = new HashSet(0);

    public Vehicle() {
    }

	
    public Vehicle(VehicleType vehicleType, String vehicleNumber, int status, Date licenceUpto, Date insuaranceUpto) {
        this.vehicleType = vehicleType;
        this.vehicleNumber = vehicleNumber;
        this.status = status;
        this.licenceUpto = licenceUpto;
        this.insuaranceUpto = insuaranceUpto;
    }
    public Vehicle(VehicleType vehicleType, String vehicleNumber, int status, Date licenceUpto, Date insuaranceUpto, Set userHasVehicles) {
       this.vehicleType = vehicleType;
       this.vehicleNumber = vehicleNumber;
       this.status = status;
       this.licenceUpto = licenceUpto;
       this.insuaranceUpto = insuaranceUpto;
       this.userHasVehicles = userHasVehicles;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public VehicleType getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(VehicleType vehicleType) {
        this.vehicleType = vehicleType;
    }
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getLicenceUpto() {
        return this.licenceUpto;
    }
    
    public void setLicenceUpto(Date licenceUpto) {
        this.licenceUpto = licenceUpto;
    }
    public Date getInsuaranceUpto() {
        return this.insuaranceUpto;
    }
    
    public void setInsuaranceUpto(Date insuaranceUpto) {
        this.insuaranceUpto = insuaranceUpto;
    }
    public Set getUserHasVehicles() {
        return this.userHasVehicles;
    }
    
    public void setUserHasVehicles(Set userHasVehicles) {
        this.userHasVehicles = userHasVehicles;
    }




}


