package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * VehicleType generated by hbm2java
 */
public class VehicleType  implements java.io.Serializable {


     private Integer idvehicleType;
     private String type;
     private int status;
     private Set vehicles = new HashSet(0);

    public VehicleType() {
    }

	
    public VehicleType(String type, int status) {
        this.type = type;
        this.status = status;
    }
    public VehicleType(String type, int status, Set vehicles) {
       this.type = type;
       this.status = status;
       this.vehicles = vehicles;
    }
   
    public Integer getIdvehicleType() {
        return this.idvehicleType;
    }
    
    public void setIdvehicleType(Integer idvehicleType) {
        this.idvehicleType = idvehicleType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Set vehicles) {
        this.vehicles = vehicles;
    }




}


