package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0



/**
 * WeightConfig generated by hbm2java
 */
public class WeightConfig  implements java.io.Serializable {


     private Integer idweightConfig;
     private WeightType weightType;
     private int value;

    public WeightConfig() {
    }

    public WeightConfig(WeightType weightType, int value) {
       this.weightType = weightType;
       this.value = value;
    }
   
    public Integer getIdweightConfig() {
        return this.idweightConfig;
    }
    
    public void setIdweightConfig(Integer idweightConfig) {
        this.idweightConfig = idweightConfig;
    }
    public WeightType getWeightType() {
        return this.weightType;
    }
    
    public void setWeightType(WeightType weightType) {
        this.weightType = weightType;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


