package hibernate;
// Generated Aug 4, 2017 12:48:05 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * WeightType generated by hbm2java
 */
public class WeightType  implements java.io.Serializable {


     private Integer idweightType;
     private String weightType;
     private int status;
     private Set rateSheets = new HashSet(0);
     private Set weightConfigs = new HashSet(0);

    public WeightType() {
    }

	
    public WeightType(String weightType, int status) {
        this.weightType = weightType;
        this.status = status;
    }
    public WeightType(String weightType, int status, Set rateSheets, Set weightConfigs) {
       this.weightType = weightType;
       this.status = status;
       this.rateSheets = rateSheets;
       this.weightConfigs = weightConfigs;
    }
   
    public Integer getIdweightType() {
        return this.idweightType;
    }
    
    public void setIdweightType(Integer idweightType) {
        this.idweightType = idweightType;
    }
    public String getWeightType() {
        return this.weightType;
    }
    
    public void setWeightType(String weightType) {
        this.weightType = weightType;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getRateSheets() {
        return this.rateSheets;
    }
    
    public void setRateSheets(Set rateSheets) {
        this.rateSheets = rateSheets;
    }
    public Set getWeightConfigs() {
        return this.weightConfigs;
    }
    
    public void setWeightConfigs(Set weightConfigs) {
        this.weightConfigs = weightConfigs;
    }




}


